### ISSUE TITLE
가설좌표 메뉴로 넘어가는 버튼은 바로 클릭이 됨

### ISSUE THREAD

**Issue by kdpark-phd** [kw-hcclab/RTW_Client#7]
기획의도 : 화살표 버튼을 누르면 선택 불이 들어오고, 그 후 next 를 누르면 넘어감
현재 상황 : 우측의 전체 버튼을 누르자마자 넘어감.

![image](https://user-images.githubusercontent.com/81862815/195803509-892bd745-ff62-40f9-8a84-0b2f27cdf695.png)

**Comment by Uddiyam** [comment]
지금 저 부분이 피그마에서는 역량 분석 결과 화면으로 넘어가는 부분인데, 아직 가설좌표 테스트 중인 상황이라서 바로 저기서 이동할 수 있도록 라우팅 해놓은 상태입니다..!

**Comment by kdpark-phd** [comment]
아하 이해했어요~  실수한줄로 착각했습니다.
